/* =========================================================================
 * Les 26 cantons suisses — données pour la carte interactive « Explorer la Suisse ».
 * x,y = position (centre) sur une carte-cartogramme schématique (viewBox 100×72),
 * approximativement géographique (ouest→est, nord→sud).
 * region : de = alémanique · fr = romand · it = italophone · multi = plurilingue.
 * nameEn / langsEn / factEn = traduction anglaise (le français reste la source).
 * ========================================================================= */

const REGION_COLORS = { de: "#5B7DB1", fr: "#C65D3B", it: "#3C9E74", multi: "#B08A34" };
const REGION_LABEL = { de: "Alémanique", fr: "Romand", it: "Italophone", multi: "Plurilingue" };
const REGION_LABEL_EN = { de: "German", fr: "French", it: "Italian", multi: "Multilingual" };

const CANTONS = [
  { code: "ZH", name: "Zurich",              capital: "Zurich",      year: 1351, region: "de",    langs: "Allemand",                       x: 48, y: 15, fact: "Plus grande ville et principal pôle économique et financier du pays.", nameEn: "Zurich", langsEn: "German", factEn: "The largest city and the country's main economic and financial hub." },
  { code: "BE", name: "Berne",               capital: "Berne",       year: 1353, region: "multi", langs: "Allemand, Français",             x: 31, y: 35, fact: "Abrite la ville fédérale ; 2ᵉ canton le plus peuplé.", nameEn: "Bern", langsEn: "German, French", factEn: "Home to the federal city; the 2nd most populous canton." },
  { code: "LU", name: "Lucerne",             capital: "Lucerne",     year: 1332, region: "de",    langs: "Allemand",                       x: 38, y: 27, fact: "Son pont de la Chapelle est l'un des plus anciens ponts de bois d'Europe.", nameEn: "Lucerne", langsEn: "German", factEn: "Its Chapel Bridge is one of the oldest wooden bridges in Europe." },
  { code: "UR", name: "Uri",                 capital: "Altdorf",     year: 1291, region: "de",    langs: "Allemand",                       x: 51, y: 38, fact: "Canton fondateur de 1291, terre de la légende de Guillaume Tell.", nameEn: "Uri", langsEn: "German", factEn: "A founding canton of 1291, home of the William Tell legend." },
  { code: "SZ", name: "Schwytz",             capital: "Schwytz",     year: 1291, region: "de",    langs: "Allemand",                       x: 52, y: 28, fact: "A donné son nom à la Suisse ; canton fondateur de 1291.", nameEn: "Schwyz", langsEn: "German", factEn: "Gave Switzerland its name; a founding canton of 1291." },
  { code: "OW", name: "Obwald",              capital: "Sarnen",      year: 1291, region: "de",    langs: "Allemand",                       x: 40, y: 39, fact: "Demi-canton ; patrie de Nicolas de Flüe, figure spirituelle de la Suisse.", nameEn: "Obwalden", langsEn: "German", factEn: "A half-canton; home of Nicholas of Flüe, a Swiss spiritual figure." },
  { code: "NW", name: "Nidwald",             capital: "Stans",       year: 1291, region: "de",    langs: "Allemand",                       x: 45, y: 33, fact: "Demi-canton de Suisse centrale, au bord du lac des Quatre-Cantons.", nameEn: "Nidwalden", langsEn: "German", factEn: "A central-Switzerland half-canton, on Lake Lucerne." },
  { code: "GL", name: "Glaris",              capital: "Glaris",      year: 1352, region: "de",    langs: "Allemand",                       x: 58, y: 31, fact: "Vote encore à main levée lors de sa Landsgemeinde annuelle.", nameEn: "Glarus", langsEn: "German", factEn: "Still votes by show of hands at its annual Landsgemeinde." },
  { code: "ZG", name: "Zoug",                capital: "Zoug",        year: 1352, region: "de",    langs: "Allemand",                       x: 47, y: 23, fact: "Petit canton réputé pour sa fiscalité avantageuse.", nameEn: "Zug", langsEn: "German", factEn: "A small canton known for its favourable taxation." },
  { code: "FR", name: "Fribourg",            capital: "Fribourg",    year: 1481, region: "multi", langs: "Français, Allemand",             x: 23, y: 36, fact: "Canton bilingue français-allemand ; patrie du fromage de Gruyère.", nameEn: "Fribourg", langsEn: "French, German", factEn: "A bilingual French–German canton; home of Gruyère cheese." },
  { code: "SO", name: "Soleure",             capital: "Soleure",     year: 1481, region: "de",    langs: "Allemand",                       x: 26, y: 20, fact: "Ville baroque où le chiffre 11 est partout (tours, cloches, fontaines).", nameEn: "Solothurn", langsEn: "German", factEn: "A baroque town where the number 11 is everywhere (towers, bells, fountains)." },
  { code: "BS", name: "Bâle-Ville",          capital: "Bâle",        year: 1501, region: "de",    langs: "Allemand",                       x: 16, y: 7,  fact: "Demi-canton urbain : grand carnaval (Fasnacht) et industrie pharmaceutique.", nameEn: "Basel-City", langsEn: "German", factEn: "An urban half-canton: famous carnival (Fasnacht) and pharma industry." },
  { code: "BL", name: "Bâle-Campagne",       capital: "Liestal",     year: 1501, region: "de",    langs: "Allemand",                       x: 19, y: 15, fact: "Demi-canton, séparé de Bâle-Ville en 1833.", nameEn: "Basel-Country", langsEn: "German", factEn: "A half-canton, split from Basel-City in 1833." },
  { code: "SH", name: "Schaffhouse",         capital: "Schaffhouse", year: 1501, region: "de",    langs: "Allemand",                       x: 49, y: 6,  fact: "Au nord du Rhin ; on y admire les chutes du Rhin, les plus grandes d'Europe.", nameEn: "Schaffhausen", langsEn: "German", factEn: "North of the Rhine; home of the Rhine Falls, the largest in Europe." },
  { code: "AR", name: "Appenzell Rh.-Ext.",  capital: "Herisau",     year: 1513, region: "de",    langs: "Allemand",                       x: 62, y: 17, fact: "Demi-canton d'Appenzell, de tradition protestante.", nameEn: "Appenzell A.Rh.", langsEn: "German", factEn: "An Appenzell half-canton, of Protestant tradition." },
  { code: "AI", name: "Appenzell Rh.-Int.",  capital: "Appenzell",   year: 1513, region: "de",    langs: "Allemand",                       x: 62, y: 24, fact: "Dernier canton à accorder le vote aux femmes (1990) ; Landsgemeinde.", nameEn: "Appenzell I.Rh.", langsEn: "German", factEn: "Last canton to grant women the vote (1990); Landsgemeinde." },
  { code: "SG", name: "Saint-Gall",          capital: "Saint-Gall",  year: 1803, region: "de",    langs: "Allemand",                       x: 70, y: 21, fact: "Sa bibliothèque abbatiale est inscrite au patrimoine mondial de l'UNESCO.", nameEn: "St. Gallen", langsEn: "German", factEn: "Its abbey library is a UNESCO World Heritage Site." },
  { code: "GR", name: "Grisons",             capital: "Coire",       year: 1803, region: "multi", langs: "Allemand, Romanche, Italien",    x: 69, y: 37, fact: "Plus grand canton et seul trilingue (allemand, romanche, italien).", nameEn: "Grisons", langsEn: "German, Romansh, Italian", factEn: "The largest canton and the only trilingual one (German, Romansh, Italian)." },
  { code: "AG", name: "Argovie",             capital: "Aarau",       year: 1803, region: "de",    langs: "Allemand",                       x: 35, y: 14, fact: "Surnommé le « canton des châteaux ».", nameEn: "Aargau", langsEn: "German", factEn: "Nicknamed the « canton of castles »." },
  { code: "TG", name: "Thurgovie",           capital: "Frauenfeld",  year: 1803, region: "de",    langs: "Allemand",                       x: 59, y: 10, fact: "Pays des vergers et des pommes, au bord du lac de Constance.", nameEn: "Thurgau", langsEn: "German", factEn: "Land of orchards and apples, on Lake Constance." },
  { code: "TI", name: "Tessin",              capital: "Bellinzone",  year: 1803, region: "it",    langs: "Italien",                        x: 55, y: 61, fact: "Seul canton de langue italienne ; les châteaux de Bellinzone sont à l'UNESCO.", nameEn: "Ticino", langsEn: "Italian", factEn: "The only Italian-speaking canton; the castles of Bellinzona are UNESCO-listed." },
  { code: "VD", name: "Vaud",                capital: "Lausanne",    year: 1803, region: "fr",    langs: "Français",                       x: 13, y: 45, fact: "Terrasses de Lavaux (UNESCO) ; Lausanne, capitale olympique.", nameEn: "Vaud", langsEn: "French", factEn: "Lavaux terraces (UNESCO); Lausanne, the Olympic Capital." },
  { code: "VS", name: "Valais",              capital: "Sion",        year: 1815, region: "multi", langs: "Français, Allemand",             x: 33, y: 53, fact: "Bilingue ; abrite le Cervin et la Pointe Dufour, plus haut sommet du pays.", nameEn: "Valais", langsEn: "French, German", factEn: "Bilingual; home of the Matterhorn and Dufourspitze, the country's highest peak." },
  { code: "NE", name: "Neuchâtel",           capital: "Neuchâtel",   year: 1815, region: "fr",    langs: "Français",                       x: 15, y: 28, fact: "Berceau de l'horlogerie de précision.", nameEn: "Neuchâtel", langsEn: "French", factEn: "The cradle of precision watchmaking." },
  { code: "GE", name: "Genève",              capital: "Genève",      year: 1815, region: "fr",    langs: "Français",                       x: 6,  y: 58, fact: "Ville internationale : siège européen de l'ONU, célèbre jet d'eau.", nameEn: "Geneva", langsEn: "French", factEn: "An international city: European seat of the UN, famous water jet." },
  { code: "JU", name: "Jura",                capital: "Delémont",    year: 1979, region: "fr",    langs: "Français",                       x: 10, y: 20, fact: "Le plus jeune canton, créé en 1979 en se séparant de Berne.", nameEn: "Jura", langsEn: "French", factEn: "The youngest canton, created in 1979 by splitting from Bern." },
];

if (typeof module !== "undefined") { module.exports = { CANTONS, REGION_COLORS, REGION_LABEL, REGION_LABEL_EN }; }
