/* =========================================================================
 * Frise chronologique — repères d'histoire.
 * scope : "ch" = Suisse (fédéral, affiché pour tous les cantons)
 *         "VD" / "GE" / "NE" / "VS" = événements propres au canton.
 * La frise n'affiche que : Suisse + le canton choisi par l'utilisateur.
 * titleEn / descEn = traduction anglaise (le français reste la source).
 * ========================================================================= */

const TIMELINE = [
  /* -------- Suisse (fédéral) -------- */
  { year: "1291", scope: "ch", title: "Pacte fédéral",
    desc: "Uri, Schwytz et Unterwald s'allient sur la prairie du Grütli : acte fondateur de la Confédération, fêté chaque 1er août.",
    titleEn: "Federal Pact",
    descEn: "Uri, Schwyz and Unterwalden form an alliance on the Rütli meadow: the founding act of the Confederation, celebrated every 1 August." },
  { year: "1315", scope: "ch", title: "Bataille de Morgarten",
    desc: "Les Confédérés remportent une première grande victoire face aux Habsbourg.",
    titleEn: "Battle of Morgarten",
    descEn: "The Confederates win a first great victory against the Habsburgs." },
  { year: "1476", scope: "ch", title: "Guerres de Bourgogne",
    desc: "Victoires confédérées à Grandson et Morat contre Charles le Téméraire.",
    titleEn: "Burgundian Wars",
    descEn: "Confederate victories at Grandson and Murten against Charles the Bold." },
  { year: "1798", scope: "ch", title: "République helvétique",
    desc: "La France impose une république centralisée ; fin de l'Ancienne Confédération.",
    titleEn: "Helvetic Republic",
    descEn: "France imposes a centralised republic; the end of the Old Confederation." },
  { year: "1815", scope: "ch", title: "Congrès de Vienne",
    desc: "La neutralité suisse est reconnue ; Genève, le Valais et Neuchâtel rejoignent la Confédération (23 cantons).",
    titleEn: "Congress of Vienna",
    descEn: "Swiss neutrality is recognised; Geneva, Valais and Neuchâtel join the Confederation (23 cantons)." },
  { year: "1848", scope: "ch", title: "Constitution fédérale",
    desc: "Après la guerre du Sonderbund, la Suisse devient un État fédéral moderne (Conseil fédéral, Parlement).",
    titleEn: "Federal Constitution",
    descEn: "After the Sonderbund war, Switzerland becomes a modern federal state (Federal Council, Parliament)." },
  { year: "1863", scope: "ch", title: "Fondation de la Croix-Rouge",
    desc: "Henri Dunant fonde la Croix-Rouge à Genève ; il recevra le tout premier prix Nobel de la paix.",
    titleEn: "Founding of the Red Cross",
    descEn: "Henry Dunant founds the Red Cross in Geneva; he would receive the very first Nobel Peace Prize." },
  { year: "1971", scope: "ch", title: "Vote des femmes (fédéral)",
    desc: "Les Suissesses obtiennent le droit de vote et d'éligibilité au niveau fédéral.",
    titleEn: "Women's suffrage (federal)",
    descEn: "Swiss women gain the right to vote and stand for election at federal level." },
  { year: "1979", scope: "ch", title: "Naissance du canton du Jura",
    desc: "Le Jura devient le 26e canton, en se séparant du canton de Berne.",
    titleEn: "Birth of the canton of Jura",
    descEn: "Jura becomes the 26th canton, splitting from the canton of Bern." },
  { year: "2002", scope: "ch", title: "La Suisse entre à l'ONU",
    desc: "Par votation populaire, la Suisse adhère à l'Organisation des Nations Unies.",
    titleEn: "Switzerland joins the UN",
    descEn: "By popular vote, Switzerland joins the United Nations." },
  { year: "2008", scope: "ch", title: "Espace Schengen",
    desc: "La Suisse rejoint l'espace Schengen (libre circulation), sans adhérer à l'Union européenne.",
    titleEn: "Schengen Area",
    descEn: "Switzerland joins the Schengen area (free movement), without joining the European Union." },

  /* -------- Vaud -------- */
  { year: "~15 av. J.-C.", scope: "VD", title: "Époque romaine",
    desc: "Rome fonde Aventicum (Avenches), capitale de l'Helvétie, ainsi que Lousonna (Lausanne) et Noviodunum (Nyon).",
    titleEn: "Roman era",
    descEn: "Rome founds Aventicum (Avenches), capital of Helvetia, as well as Lousonna (Lausanne) and Noviodunum (Nyon)." },
  { year: "1536", scope: "VD", title: "Berne conquiert Vaud",
    desc: "Berne s'empare du Pays de Vaud et y impose la Réforme. Vaud restera bernois jusqu'en 1798.",
    titleEn: "Bern conquers Vaud",
    descEn: "Bern seizes the Vaud region and imposes the Reformation. Vaud will remain Bernese until 1798." },
  { year: "1723", scope: "VD", title: "Révolte du Major Davel",
    desc: "Le patriote vaudois tente de libérer Vaud de la tutelle bernoise ; il est décapité.",
    titleEn: "Major Davel's revolt",
    descEn: "The Vaud patriot tries to free Vaud from Bernese rule; he is beheaded." },
  { year: "1798", scope: "VD", title: "Indépendance vaudoise",
    desc: "Le 24 janvier, le Pays de Vaud proclame son indépendance (République lémanique).",
    titleEn: "Vaud independence",
    descEn: "On 24 January, the Vaud region proclaims its independence (Lemanic Republic)." },
  { year: "1803", scope: "VD", title: "Vaud rejoint la Confédération",
    desc: "L'Acte de Médiation de Napoléon fait de Vaud un canton suisse à part entière (14 avril).",
    titleEn: "Vaud joins the Confederation",
    descEn: "Napoleon's Act of Mediation makes Vaud a full Swiss canton (14 April)." },
  { year: "1959", scope: "VD", title: "Vaud, pionnier du vote des femmes",
    desc: "Vaud est le premier canton à accorder le droit de vote aux femmes au niveau cantonal.",
    titleEn: "Vaud, pioneer of women's suffrage",
    descEn: "Vaud is the first canton to grant women the right to vote at cantonal level." },
  { year: "2007", scope: "VD", title: "Lavaux au patrimoine de l'UNESCO",
    desc: "Les terrasses viticoles de Lavaux, entre Lausanne et Montreux, sont inscrites à l'UNESCO.",
    titleEn: "Lavaux, UNESCO World Heritage",
    descEn: "The Lavaux vineyard terraces, between Lausanne and Montreux, are listed by UNESCO." },
  { year: "2019", scope: "VD", title: "Fête des Vignerons",
    desc: "La Fête des Vignerons de Vevey (patrimoine immatériel de l'UNESCO) rassemble des centaines de milliers de visiteurs.",
    titleEn: "Winegrowers' Festival",
    descEn: "The Winegrowers' Festival in Vevey (UNESCO intangible heritage) draws hundreds of thousands of visitors." },

  /* -------- Genève -------- */
  { year: "1536", scope: "GE", title: "La Réforme à Genève",
    desc: "Genève adopte la Réforme ; Jean Calvin en fait la « Rome protestante ».",
    titleEn: "The Reformation in Geneva",
    descEn: "Geneva adopts the Reformation; John Calvin makes it the « Protestant Rome »." },
  { year: "1602", scope: "GE", title: "L'Escalade",
    desc: "Dans la nuit du 11 au 12 décembre, Genève repousse l'attaque du duc de Savoie. Fêté chaque 12 décembre.",
    titleEn: "The Escalade",
    descEn: "On the night of 11–12 December, Geneva repels the Duke of Savoy's attack. Celebrated every 12 December." },
  { year: "1815", scope: "GE", title: "Genève rejoint la Confédération",
    desc: "Après l'entrée des troupes suisses au Port-Noir (1814), Genève devient un canton suisse.",
    titleEn: "Geneva joins the Confederation",
    descEn: "After Swiss troops land at Port-Noir (1814), Geneva becomes a Swiss canton." },
  { year: "1920", scope: "GE", title: "La Société des Nations",
    desc: "La SDN s'installe à Genève : c'est le début de la « Genève internationale ».",
    titleEn: "The League of Nations",
    descEn: "The League of Nations settles in Geneva: the start of « International Geneva »." },
  { year: "1946", scope: "GE", title: "Siège européen de l'ONU",
    desc: "L'ONU installe son siège européen à Genève (Palais des Nations).",
    titleEn: "European seat of the UN",
    descEn: "The UN establishes its European headquarters in Geneva (Palais des Nations)." },

  /* -------- Neuchâtel -------- */
  { year: "1707", scope: "NE", title: "Neuchâtel à la Prusse",
    desc: "La principauté de Neuchâtel passe au roi de Prusse.",
    titleEn: "Neuchâtel to Prussia",
    descEn: "The principality of Neuchâtel passes to the King of Prussia." },
  { year: "1815", scope: "NE", title: "Neuchâtel rejoint la Confédération",
    desc: "Neuchâtel entre dans la Confédération — tout en restant une principauté prussienne (cas unique en Suisse).",
    titleEn: "Neuchâtel joins the Confederation",
    descEn: "Neuchâtel joins the Confederation — while remaining a Prussian principality (unique in Switzerland)." },
  { year: "1848", scope: "NE", title: "La République neuchâteloise",
    desc: "La révolution met fin à la principauté : Neuchâtel devient une République.",
    titleEn: "The Neuchâtel Republic",
    descEn: "The revolution ends the principality: Neuchâtel becomes a Republic." },
  { year: "1849", scope: "NE", title: "Vote des étrangers",
    desc: "La Constitution accorde le droit de vote communal aux étrangers — une première en Suisse.",
    titleEn: "Foreigners' vote",
    descEn: "The Constitution grants foreigners the right to vote at communal level — a first in Switzerland." },
  { year: "2009", scope: "NE", title: "Urbanisme horloger à l'UNESCO",
    desc: "La Chaux-de-Fonds et Le Locle, villes de l'horlogerie, sont inscrites au patrimoine mondial.",
    titleEn: "Watchmaking towns at UNESCO",
    descEn: "La Chaux-de-Fonds and Le Locle, watchmaking towns, are listed as World Heritage." },

  /* -------- Valais -------- */
  { year: "1802", scope: "VS", title: "République du Valais",
    desc: "Éphémère République indépendante du Valais (République rhodanienne).",
    titleEn: "Republic of Valais",
    descEn: "The short-lived independent Republic of Valais (Rhodanic Republic)." },
  { year: "1810", scope: "VS", title: "Annexion française",
    desc: "Napoléon annexe le Valais : il devient le département du Simplon.",
    titleEn: "French annexation",
    descEn: "Napoleon annexes Valais: it becomes the department of Simplon." },
  { year: "1815", scope: "VS", title: "Le Valais rejoint la Confédération",
    desc: "Le Valais devient un canton suisse à part entière (23 cantons).",
    titleEn: "Valais joins the Confederation",
    descEn: "Valais becomes a full Swiss canton (23 cantons)." },
  { year: "1865", scope: "VS", title: "Première ascension du Cervin",
    desc: "Edward Whymper gravit le Cervin depuis Zermatt ; la descente tourne au drame.",
    titleEn: "First ascent of the Matterhorn",
    descEn: "Edward Whymper climbs the Matterhorn from Zermatt; the descent ends in tragedy." },
  { year: "1964", scope: "VS", title: "Tunnel du Grand-Saint-Bernard",
    desc: "Ouverture du premier tunnel routier des Alpes, reliant le Valais à l'Italie.",
    titleEn: "Great St Bernard Tunnel",
    descEn: "Opening of the first road tunnel in the Alps, linking Valais to Italy." },
];

if (typeof module !== "undefined") { module.exports = { TIMELINE }; }
