/* =========================================================================
 * Frise chronologique — repères d'histoire.
 * scope : "ch" = Suisse (fédéral, affiché pour tous les cantons)
 *         "VD" / "GE" / "NE" / "VS" = événements propres au canton.
 * title/desc = FR (source) ; suffixes En/Pt/Es/It/De/Sq = traductions.
 * ========================================================================= */

const TIMELINE = [
  /* -------- Suisse (fédéral) -------- */
  { year: "1291", scope: "ch", title: "Pacte fédéral",
    desc: "Uri, Schwytz et Unterwald s'allient sur la prairie du Grütli : acte fondateur de la Confédération, fêté chaque 1er août.",
    titleEn: "Federal Pact", descEn: "Uri, Schwyz and Unterwalden form an alliance on the Rütli meadow: the founding act of the Confederation, celebrated every 1 August.",
    titlePt: "Pacto Federal", descPt: "Uri, Schwyz e Unterwalden aliam-se no prado do Grütli: ato fundador da Confederação, celebrado a 1 de agosto.",
    titleEs: "Pacto Federal", descEs: "Uri, Schwyz y Unterwalden se alían en la pradera del Rütli: acto fundador de la Confederación, celebrado cada 1 de agosto.",
    titleIt: "Patto federale", descIt: "Uri, Svitto e Untervaldo si alleano sul prato del Rütli: atto fondativo della Confederazione, festeggiato ogni 1° agosto.",
    titleDe: "Bundesbrief", descDe: "Uri, Schwyz und Unterwalden verbünden sich auf der Rütliwiese: der Gründungsakt der Eidgenossenschaft, jedes Jahr am 1. August gefeiert.",
    titleSq: "Pakti federal", descSq: "Uri, Schwyz dhe Unterwalden lidhin aleancë në livadhin e Rütli-t: akti themelues i Konfederatës, festuar çdo 1 gusht." },
  { year: "1315", scope: "ch", title: "Bataille de Morgarten",
    desc: "Les Confédérés remportent une première grande victoire face aux Habsbourg.",
    titleEn: "Battle of Morgarten", descEn: "The Confederates win a first great victory against the Habsburgs.",
    titlePt: "Batalha de Morgarten", descPt: "Os Confederados obtêm uma primeira grande vitória sobre os Habsburgo.",
    titleEs: "Batalla de Morgarten", descEs: "Los Confederados logran una primera gran victoria frente a los Habsburgo.",
    titleIt: "Battaglia di Morgarten", descIt: "I Confederati ottengono una prima grande vittoria contro gli Asburgo.",
    titleDe: "Schlacht am Morgarten", descDe: "Die Eidgenossen erringen einen ersten grossen Sieg gegen die Habsburger.",
    titleSq: "Beteja e Morgarten", descSq: "Konfederatët fitojnë një fitore të parë të madhe kundër Habsburgëve." },
  { year: "1476", scope: "ch", title: "Guerres de Bourgogne",
    desc: "Victoires confédérées à Grandson et Morat contre Charles le Téméraire.",
    titleEn: "Burgundian Wars", descEn: "Confederate victories at Grandson and Murten against Charles the Bold.",
    titlePt: "Guerras da Borgonha", descPt: "Vitórias confederadas em Grandson e Morat contra Carlos, o Temerário.",
    titleEs: "Guerras de Borgoña", descEs: "Victorias confederadas en Grandson y Morat contra Carlos el Temerario.",
    titleIt: "Guerre di Borgogna", descIt: "Vittorie confederate a Grandson e Morat contro Carlo il Temerario.",
    titleDe: "Burgunderkriege", descDe: "Eidgenössische Siege bei Grandson und Murten gegen Karl den Kühnen.",
    titleSq: "Luftërat e Burgonjës", descSq: "Fitore konfederate në Grandson dhe Morat kundër Karlit të Guximshëm." },
  { year: "1798", scope: "ch", title: "République helvétique",
    desc: "La France impose une république centralisée ; fin de l'Ancienne Confédération.",
    titleEn: "Helvetic Republic", descEn: "France imposes a centralised republic; the end of the Old Confederation.",
    titlePt: "República Helvética", descPt: "A França impõe uma república centralizada; fim da Antiga Confederação.",
    titleEs: "República Helvética", descEs: "Francia impone una república centralizada; fin de la Antigua Confederación.",
    titleIt: "Repubblica Elvetica", descIt: "La Francia impone una repubblica centralizzata; fine dell'Antica Confederazione.",
    titleDe: "Helvetische Republik", descDe: "Frankreich erzwingt eine zentralisierte Republik; Ende der Alten Eidgenossenschaft.",
    titleSq: "Republika Helvetike", descSq: "Franca imponon një republikë të centralizuar; fundi i Konfederatës së Vjetër." },
  { year: "1815", scope: "ch", title: "Congrès de Vienne",
    desc: "La neutralité suisse est reconnue ; Genève, le Valais et Neuchâtel rejoignent la Confédération (23 cantons).",
    titleEn: "Congress of Vienna", descEn: "Swiss neutrality is recognised; Geneva, Valais and Neuchâtel join the Confederation (23 cantons).",
    titlePt: "Congresso de Viena", descPt: "A neutralidade suíça é reconhecida; Genebra, Valais e Neuchâtel juntam-se à Confederação (23 cantões).",
    titleEs: "Congreso de Viena", descEs: "Se reconoce la neutralidad suiza; Ginebra, Valais y Neuchâtel se unen a la Confederación (23 cantones).",
    titleIt: "Congresso di Vienna", descIt: "La neutralità svizzera è riconosciuta; Ginevra, Vallese e Neuchâtel entrano nella Confederazione (23 cantoni).",
    titleDe: "Wiener Kongress", descDe: "Die Schweizer Neutralität wird anerkannt; Genf, Wallis und Neuenburg treten der Eidgenossenschaft bei (23 Kantone).",
    titleSq: "Kongresi i Vjenës", descSq: "Neutraliteti zviceran njihet; Gjeneva, Valais dhe Neuchâtel i bashkohen Konfederatës (23 kantone)." },
  { year: "1848", scope: "ch", title: "Constitution fédérale",
    desc: "Après la guerre du Sonderbund, la Suisse devient un État fédéral moderne (Conseil fédéral, Parlement).",
    titleEn: "Federal Constitution", descEn: "After the Sonderbund war, Switzerland becomes a modern federal state (Federal Council, Parliament).",
    titlePt: "Constituição Federal", descPt: "Após a guerra do Sonderbund, a Suíça torna-se um Estado federal moderno (Conselho Federal, Parlamento).",
    titleEs: "Constitución Federal", descEs: "Tras la guerra del Sonderbund, Suiza se convierte en un Estado federal moderno (Consejo Federal, Parlamento).",
    titleIt: "Costituzione federale", descIt: "Dopo la guerra del Sonderbund, la Svizzera diventa uno Stato federale moderno (Consiglio federale, Parlamento).",
    titleDe: "Bundesverfassung", descDe: "Nach dem Sonderbundskrieg wird die Schweiz ein moderner Bundesstaat (Bundesrat, Parlament).",
    titleSq: "Kushtetuta federale", descSq: "Pas luftës së Sonderbund-it, Zvicra bëhet një shtet federal modern (Këshilli Federal, Parlamenti)." },
  { year: "1863", scope: "ch", title: "Fondation de la Croix-Rouge",
    desc: "Henri Dunant fonde la Croix-Rouge à Genève ; il recevra le tout premier prix Nobel de la paix.",
    titleEn: "Founding of the Red Cross", descEn: "Henry Dunant founds the Red Cross in Geneva; he would receive the very first Nobel Peace Prize.",
    titlePt: "Fundação da Cruz Vermelha", descPt: "Henri Dunant funda a Cruz Vermelha em Genebra; receberá o primeiro Prémio Nobel da Paz.",
    titleEs: "Fundación de la Cruz Roja", descEs: "Henri Dunant funda la Cruz Roja en Ginebra; recibirá el primer Premio Nobel de la Paz.",
    titleIt: "Fondazione della Croce Rossa", descIt: "Henry Dunant fonda la Croce Rossa a Ginevra; riceverà il primo Premio Nobel per la pace.",
    titleDe: "Gründung des Roten Kreuzes", descDe: "Henry Dunant gründet das Rote Kreuz in Genf; er erhält den allerersten Friedensnobelpreis.",
    titleSq: "Themelimi i Kryqit të Kuq", descSq: "Henry Dunant themelon Kryqin e Kuq në Gjenevë; do të marrë Çmimin e parë Nobel për Paqen." },
  { year: "1971", scope: "ch", title: "Vote des femmes (fédéral)",
    desc: "Les Suissesses obtiennent le droit de vote et d'éligibilité au niveau fédéral.",
    titleEn: "Women's suffrage (federal)", descEn: "Swiss women gain the right to vote and stand for election at federal level.",
    titlePt: "Voto das mulheres (federal)", descPt: "As suíças obtêm o direito de voto e de elegibilidade a nível federal.",
    titleEs: "Voto de las mujeres (federal)", descEs: "Las suizas obtienen el derecho de voto y de elegibilidad a nivel federal.",
    titleIt: "Voto alle donne (federale)", descIt: "Le svizzere ottengono il diritto di voto e di eleggibilità a livello federale.",
    titleDe: "Frauenstimmrecht (Bund)", descDe: "Die Schweizerinnen erhalten auf Bundesebene das Stimm- und Wahlrecht.",
    titleSq: "Vota e grave (federale)", descSq: "Zvicerankat fitojnë të drejtën e votës dhe të zgjedhjes në nivel federal." },
  { year: "1979", scope: "ch", title: "Naissance du canton du Jura",
    desc: "Le Jura devient le 26e canton, en se séparant du canton de Berne.",
    titleEn: "Birth of the canton of Jura", descEn: "Jura becomes the 26th canton, splitting from the canton of Bern.",
    titlePt: "Nascimento do cantão do Jura", descPt: "O Jura torna-se o 26.º cantão, separando-se do cantão de Berna.",
    titleEs: "Nacimiento del cantón del Jura", descEs: "El Jura se convierte en el 26.º cantón, separándose del cantón de Berna.",
    titleIt: "Nascita del cantone del Giura", descIt: "Il Giura diventa il 26º cantone, separandosi dal cantone di Berna.",
    titleDe: "Gründung des Kantons Jura", descDe: "Der Jura wird durch Abspaltung von Bern zum 26. Kanton.",
    titleSq: "Lindja e kantonit të Jurës", descSq: "Jura bëhet kantoni i 26-të, duke u ndarë nga kantoni i Bernës." },
  { year: "2002", scope: "ch", title: "La Suisse entre à l'ONU",
    desc: "Par votation populaire, la Suisse adhère à l'Organisation des Nations Unies.",
    titleEn: "Switzerland joins the UN", descEn: "By popular vote, Switzerland joins the United Nations.",
    titlePt: "A Suíça entra na ONU", descPt: "Por votação popular, a Suíça adere à Organização das Nações Unidas.",
    titleEs: "Suiza entra en la ONU", descEs: "Por votación popular, Suiza se adhiere a la Organización de las Naciones Unidas.",
    titleIt: "La Svizzera entra nell'ONU", descIt: "Con votazione popolare, la Svizzera aderisce all'Organizzazione delle Nazioni Unite.",
    titleDe: "Die Schweiz tritt der UNO bei", descDe: "Durch Volksabstimmung tritt die Schweiz den Vereinten Nationen bei.",
    titleSq: "Zvicra hyn në OKB", descSq: "Me votim popullor, Zvicra anëtarësohet në Organizatën e Kombeve të Bashkuara." },
  { year: "2008", scope: "ch", title: "Espace Schengen",
    desc: "La Suisse rejoint l'espace Schengen (libre circulation), sans adhérer à l'Union européenne.",
    titleEn: "Schengen Area", descEn: "Switzerland joins the Schengen area (free movement), without joining the European Union.",
    titlePt: "Espaço Schengen", descPt: "A Suíça adere ao espaço Schengen (livre circulação), sem aderir à União Europeia.",
    titleEs: "Espacio Schengen", descEs: "Suiza se une al espacio Schengen (libre circulación), sin adherirse a la Unión Europea.",
    titleIt: "Spazio Schengen", descIt: "La Svizzera aderisce allo spazio Schengen (libera circolazione), senza aderire all'Unione europea.",
    titleDe: "Schengen-Raum", descDe: "Die Schweiz tritt dem Schengen-Raum bei (Freizügigkeit), ohne der Europäischen Union beizutreten.",
    titleSq: "Zona Schengen", descSq: "Zvicra i bashkohet zonës Schengen (lëvizje e lirë), pa iu bashkuar Bashkimit Evropian." },

  /* -------- Vaud -------- */
  { year: "~15 av. J.-C.", scope: "VD", title: "Époque romaine",
    desc: "Rome fonde Aventicum (Avenches), capitale de l'Helvétie, ainsi que Lousonna (Lausanne) et Noviodunum (Nyon).",
    titleEn: "Roman era", descEn: "Rome founds Aventicum (Avenches), capital of Helvetia, as well as Lousonna (Lausanne) and Noviodunum (Nyon).",
    titlePt: "Época romana", descPt: "Roma funda Aventicum (Avenches), capital da Helvécia, bem como Lousonna (Lausanne) e Noviodunum (Nyon).",
    titleEs: "Época romana", descEs: "Roma funda Aventicum (Avenches), capital de Helvecia, así como Lousonna (Lausana) y Noviodunum (Nyon).",
    titleIt: "Epoca romana", descIt: "Roma fonda Aventicum (Avenches), capitale dell'Elvezia, oltre a Lousonna (Losanna) e Noviodunum (Nyon).",
    titleDe: "Römerzeit", descDe: "Rom gründet Aventicum (Avenches), Hauptstadt Helvetiens, sowie Lousonna (Lausanne) und Noviodunum (Nyon).",
    titleSq: "Epoka romake", descSq: "Roma themelon Aventicum (Avenches), kryeqytetin e Helvecisë, si dhe Lousonna (Lozanë) dhe Noviodunum (Nyon)." },
  { year: "1536", scope: "VD", title: "Berne conquiert Vaud",
    desc: "Berne s'empare du Pays de Vaud et y impose la Réforme. Vaud restera bernois jusqu'en 1798.",
    titleEn: "Bern conquers Vaud", descEn: "Bern seizes the Vaud region and imposes the Reformation. Vaud will remain Bernese until 1798.",
    titlePt: "Berna conquista Vaud", descPt: "Berna apodera-se do País de Vaud e impõe a Reforma. Vaud permanecerá bernês até 1798.",
    titleEs: "Berna conquista Vaud", descEs: "Berna se apodera del País de Vaud e impone la Reforma. Vaud seguirá siendo bernés hasta 1798.",
    titleIt: "Berna conquista Vaud", descIt: "Berna si impadronisce del Paese di Vaud e vi impone la Riforma. Vaud resterà bernese fino al 1798.",
    titleDe: "Bern erobert die Waadt", descDe: "Bern erobert das Waadtland und führt die Reformation ein. Die Waadt bleibt bis 1798 bernisch.",
    titleSq: "Berna pushton Vaud-in", descSq: "Berna zaptohet nga Vendi i Vaud-it dhe imponon Reformën. Vaud do të mbetet bernez deri më 1798." },
  { year: "1723", scope: "VD", title: "Révolte du Major Davel",
    desc: "Le patriote vaudois tente de libérer Vaud de la tutelle bernoise ; il est décapité.",
    titleEn: "Major Davel's revolt", descEn: "The Vaud patriot tries to free Vaud from Bernese rule; he is beheaded.",
    titlePt: "Revolta do Major Davel", descPt: "O patriota de Vaud tenta libertar Vaud da tutela bernesa; é decapitado.",
    titleEs: "Revuelta del Mayor Davel", descEs: "El patriota vaudés intenta liberar Vaud de la tutela bernesa; es decapitado.",
    titleIt: "Rivolta del Maggiore Davel", descIt: "Il patriota vodese tenta di liberare Vaud dalla tutela bernese; viene decapitato.",
    titleDe: "Aufstand von Major Davel", descDe: "Der Waadtländer Patriot versucht, die Waadt von der bernischen Herrschaft zu befreien; er wird enthauptet.",
    titleSq: "Kryengritja e Major Davel", descSq: "Patrioti i Vaud-it përpiqet ta çlirojë Vaud-in nga sundimi bernez; ai dekapitohet." },
  { year: "1798", scope: "VD", title: "Indépendance vaudoise",
    desc: "Le 24 janvier, le Pays de Vaud proclame son indépendance (République lémanique).",
    titleEn: "Vaud independence", descEn: "On 24 January, the Vaud region proclaims its independence (Lemanic Republic).",
    titlePt: "Independência de Vaud", descPt: "A 24 de janeiro, o País de Vaud proclama a sua independência (República Lemânica).",
    titleEs: "Independencia de Vaud", descEs: "El 24 de enero, el País de Vaud proclama su independencia (República Lemánica).",
    titleIt: "Indipendenza vodese", descIt: "Il 24 gennaio, il Paese di Vaud proclama la sua indipendenza (Repubblica Lemanica).",
    titleDe: "Waadtländer Unabhängigkeit", descDe: "Am 24. Januar ruft das Waadtland seine Unabhängigkeit aus (Lemanische Republik).",
    titleSq: "Pavarësia e Vaud-it", descSq: "Më 24 janar, Vendi i Vaud-it shpall pavarësinë e vet (Republika Lemanike)." },
  { year: "1803", scope: "VD", title: "Vaud rejoint la Confédération",
    desc: "L'Acte de Médiation de Napoléon fait de Vaud un canton suisse à part entière (14 avril).",
    titleEn: "Vaud joins the Confederation", descEn: "Napoleon's Act of Mediation makes Vaud a full Swiss canton (14 April).",
    titlePt: "Vaud junta-se à Confederação", descPt: "O Ato de Mediação de Napoleão faz de Vaud um cantão suíço de pleno direito (14 de abril).",
    titleEs: "Vaud se une a la Confederación", descEs: "El Acta de Mediación de Napoleón hace de Vaud un cantón suizo de pleno derecho (14 de abril).",
    titleIt: "Vaud entra nella Confederazione", descIt: "L'Atto di Mediazione di Napoleone fa di Vaud un cantone svizzero a pieno titolo (14 aprile).",
    titleDe: "Die Waadt tritt der Eidgenossenschaft bei", descDe: "Napoleons Mediationsakte macht die Waadt zu einem vollwertigen Schweizer Kanton (14. April).",
    titleSq: "Vaud i bashkohet Konfederatës", descSq: "Akti i Ndërmjetësimit i Napoleonit e bën Vaud-in një kanton zviceran të plotë (14 prill)." },
  { year: "1959", scope: "VD", title: "Vaud, pionnier du vote des femmes",
    desc: "Vaud est le premier canton à accorder le droit de vote aux femmes au niveau cantonal.",
    titleEn: "Vaud, pioneer of women's suffrage", descEn: "Vaud is the first canton to grant women the right to vote at cantonal level.",
    titlePt: "Vaud, pioneiro do voto das mulheres", descPt: "Vaud é o primeiro cantão a conceder o direito de voto às mulheres a nível cantonal.",
    titleEs: "Vaud, pionero del voto femenino", descEs: "Vaud es el primer cantón en conceder el derecho de voto a las mujeres a nivel cantonal.",
    titleIt: "Vaud, pioniere del voto alle donne", descIt: "Vaud è il primo cantone a concedere il diritto di voto alle donne a livello cantonale.",
    titleDe: "Waadt, Pionier des Frauenstimmrechts", descDe: "Die Waadt ist der erste Kanton, der den Frauen auf Kantonsebene das Stimmrecht gewährt.",
    titleSq: "Vaud, pionier i votës së grave", descSq: "Vaud është kantoni i parë që u jep grave të drejtën e votës në nivel kantonal." },
  { year: "2007", scope: "VD", title: "Lavaux au patrimoine de l'UNESCO",
    desc: "Les terrasses viticoles de Lavaux, entre Lausanne et Montreux, sont inscrites à l'UNESCO.",
    titleEn: "Lavaux, UNESCO World Heritage", descEn: "The Lavaux vineyard terraces, between Lausanne and Montreux, are listed by UNESCO.",
    titlePt: "Lavaux, Património da UNESCO", descPt: "Os terraços vinícolas de Lavaux, entre Lausanne e Montreux, são inscritos na UNESCO.",
    titleEs: "Lavaux, Patrimonio de la UNESCO", descEs: "Las terrazas vinícolas de Lavaux, entre Lausana y Montreux, se inscriben en la UNESCO.",
    titleIt: "Lavaux, Patrimonio UNESCO", descIt: "Le terrazze vitivinicole di Lavaux, tra Losanna e Montreux, sono iscritte all'UNESCO.",
    titleDe: "Lavaux, UNESCO-Welterbe", descDe: "Die Weinterrassen von Lavaux zwischen Lausanne und Montreux werden ins UNESCO-Welterbe aufgenommen.",
    titleSq: "Lavaux, Trashëgimi e UNESCO-s", descSq: "Tarracat vreshtare të Lavaux, mes Lozanës dhe Montreux-së, regjistrohen në UNESCO." },
  { year: "2019", scope: "VD", title: "Fête des Vignerons",
    desc: "La Fête des Vignerons de Vevey (patrimoine immatériel de l'UNESCO) rassemble des centaines de milliers de visiteurs.",
    titleEn: "Winegrowers' Festival", descEn: "The Winegrowers' Festival in Vevey (UNESCO intangible heritage) draws hundreds of thousands of visitors.",
    titlePt: "Festa dos Vinhateiros", descPt: "A Festa dos Vinhateiros de Vevey (património imaterial da UNESCO) reúne centenas de milhares de visitantes.",
    titleEs: "Fiesta de los Viñadores", descEs: "La Fiesta de los Viñadores de Vevey (patrimonio inmaterial de la UNESCO) reúne a cientos de miles de visitantes.",
    titleIt: "Festa dei vignaioli", descIt: "La Festa dei vignaioli di Vevey (patrimonio immateriale UNESCO) richiama centinaia di migliaia di visitatori.",
    titleDe: "Winzerfest", descDe: "Das Winzerfest in Vevey (immaterielles UNESCO-Kulturerbe) zieht Hunderttausende Besucher an.",
    titleSq: "Festa e vreshtarëve", descSq: "Festa e vreshtarëve në Vevey (trashëgimi jomateriale e UNESCO-s) mbledh qindra mijëra vizitorë." },

  /* -------- Genève -------- */
  { year: "1536", scope: "GE", title: "La Réforme à Genève",
    desc: "Genève adopte la Réforme ; Jean Calvin en fait la « Rome protestante ».",
    titleEn: "The Reformation in Geneva", descEn: "Geneva adopts the Reformation; John Calvin makes it the « Protestant Rome ».",
    titlePt: "A Reforma em Genebra", descPt: "Genebra adota a Reforma; João Calvino faz dela a « Roma protestante ».",
    titleEs: "La Reforma en Ginebra", descEs: "Ginebra adopta la Reforma; Juan Calvino la convierte en la « Roma protestante ».",
    titleIt: "La Riforma a Ginevra", descIt: "Ginevra adotta la Riforma; Giovanni Calvino ne fa la « Roma protestante ».",
    titleDe: "Die Reformation in Genf", descDe: "Genf nimmt die Reformation an; Johannes Calvin macht es zum « protestantischen Rom ».",
    titleSq: "Reforma në Gjenevë", descSq: "Gjeneva pranon Reformën; Zhan Kalvini e bën « Romën protestante »." },
  { year: "1602", scope: "GE", title: "L'Escalade",
    desc: "Dans la nuit du 11 au 12 décembre, Genève repousse l'attaque du duc de Savoie. Fêté chaque 12 décembre.",
    titleEn: "The Escalade", descEn: "On the night of 11–12 December, Geneva repels the Duke of Savoy's attack. Celebrated every 12 December.",
    titlePt: "A Escalada", descPt: "Na noite de 11 para 12 de dezembro, Genebra repele o ataque do duque de Saboia. Celebrado a 12 de dezembro.",
    titleEs: "La Escalada", descEs: "En la noche del 11 al 12 de diciembre, Ginebra rechaza el ataque del duque de Saboya. Se celebra cada 12 de diciembre.",
    titleIt: "L'Escalade", descIt: "Nella notte tra l'11 e il 12 dicembre, Ginevra respinge l'attacco del duca di Savoia. Festeggiato ogni 12 dicembre.",
    titleDe: "Die Escalade", descDe: "In der Nacht vom 11. auf den 12. Dezember wehrt Genf den Angriff des Herzogs von Savoyen ab. Jedes Jahr am 12. Dezember gefeiert.",
    titleSq: "Escalade", descSq: "Natën e 11 me 12 dhjetor, Gjeneva zmbraps sulmin e dukës së Savojës. Festuar çdo 12 dhjetor." },
  { year: "1815", scope: "GE", title: "Genève rejoint la Confédération",
    desc: "Après l'entrée des troupes suisses au Port-Noir (1814), Genève devient un canton suisse.",
    titleEn: "Geneva joins the Confederation", descEn: "After Swiss troops land at Port-Noir (1814), Geneva becomes a Swiss canton.",
    titlePt: "Genebra junta-se à Confederação", descPt: "Após a entrada das tropas suíças no Port-Noir (1814), Genebra torna-se um cantão suíço.",
    titleEs: "Ginebra se une a la Confederación", descEs: "Tras la entrada de las tropas suizas en Port-Noir (1814), Ginebra se convierte en cantón suizo.",
    titleIt: "Ginevra entra nella Confederazione", descIt: "Dopo l'arrivo delle truppe svizzere al Port-Noir (1814), Ginevra diventa un cantone svizzero.",
    titleDe: "Genf tritt der Eidgenossenschaft bei", descDe: "Nach dem Einzug der Schweizer Truppen am Port-Noir (1814) wird Genf ein Schweizer Kanton.",
    titleSq: "Gjeneva i bashkohet Konfederatës", descSq: "Pas hyrjes së trupave zvicerane në Port-Noir (1814), Gjeneva bëhet një kanton zviceran." },
  { year: "1920", scope: "GE", title: "La Société des Nations",
    desc: "La SDN s'installe à Genève : c'est le début de la « Genève internationale ».",
    titleEn: "The League of Nations", descEn: "The League of Nations settles in Geneva: the start of « International Geneva ».",
    titlePt: "A Sociedade das Nações", descPt: "A SDN instala-se em Genebra: é o início da « Genebra internacional ».",
    titleEs: "La Sociedad de Naciones", descEs: "La SDN se instala en Ginebra: es el inicio de la « Ginebra internacional ».",
    titleIt: "La Società delle Nazioni", descIt: "La SDN si insedia a Ginevra: è l'inizio della « Ginevra internazionale ».",
    titleDe: "Der Völkerbund", descDe: "Der Völkerbund lässt sich in Genf nieder: der Beginn des « internationalen Genf ».",
    titleSq: "Lidhja e Kombeve", descSq: "Lidhja e Kombeve vendoset në Gjenevë: fillimi i « Gjenevës ndërkombëtare »." },
  { year: "1946", scope: "GE", title: "Siège européen de l'ONU",
    desc: "L'ONU installe son siège européen à Genève (Palais des Nations).",
    titleEn: "European seat of the UN", descEn: "The UN establishes its European headquarters in Geneva (Palais des Nations).",
    titlePt: "Sede europeia da ONU", descPt: "A ONU instala a sua sede europeia em Genebra (Palácio das Nações).",
    titleEs: "Sede europea de la ONU", descEs: "La ONU instala su sede europea en Ginebra (Palacio de las Naciones).",
    titleIt: "Sede europea dell'ONU", descIt: "L'ONU insedia la sua sede europea a Ginevra (Palazzo delle Nazioni).",
    titleDe: "Europäischer UNO-Sitz", descDe: "Die UNO richtet ihren europäischen Sitz in Genf ein (Palais des Nations).",
    titleSq: "Selia evropiane e OKB-së", descSq: "OKB-ja vendos selinë e vet evropiane në Gjenevë (Pallati i Kombeve)." },

  /* -------- Neuchâtel -------- */
  { year: "1707", scope: "NE", title: "Neuchâtel à la Prusse",
    desc: "La principauté de Neuchâtel passe au roi de Prusse.",
    titleEn: "Neuchâtel to Prussia", descEn: "The principality of Neuchâtel passes to the King of Prussia.",
    titlePt: "Neuchâtel para a Prússia", descPt: "O principado de Neuchâtel passa para o rei da Prússia.",
    titleEs: "Neuchâtel a Prusia", descEs: "El principado de Neuchâtel pasa al rey de Prusia.",
    titleIt: "Neuchâtel alla Prussia", descIt: "Il principato di Neuchâtel passa al re di Prussia.",
    titleDe: "Neuenburg an Preussen", descDe: "Das Fürstentum Neuenburg fällt an den König von Preussen.",
    titleSq: "Neuchâtel te Prusia", descSq: "Principata e Neuchâtel kalon te mbreti i Prusisë." },
  { year: "1815", scope: "NE", title: "Neuchâtel rejoint la Confédération",
    desc: "Neuchâtel entre dans la Confédération — tout en restant une principauté prussienne (cas unique en Suisse).",
    titleEn: "Neuchâtel joins the Confederation", descEn: "Neuchâtel joins the Confederation — while remaining a Prussian principality (unique in Switzerland).",
    titlePt: "Neuchâtel junta-se à Confederação", descPt: "Neuchâtel entra na Confederação — permanecendo um principado prussiano (caso único na Suíça).",
    titleEs: "Neuchâtel se une a la Confederación", descEs: "Neuchâtel entra en la Confederación — sin dejar de ser un principado prusiano (caso único en Suiza).",
    titleIt: "Neuchâtel entra nella Confederazione", descIt: "Neuchâtel entra nella Confederazione — pur restando un principato prussiano (caso unico in Svizzera).",
    titleDe: "Neuenburg tritt der Eidgenossenschaft bei", descDe: "Neuenburg tritt der Eidgenossenschaft bei — bleibt aber ein preussisches Fürstentum (einzigartig in der Schweiz).",
    titleSq: "Neuchâtel i bashkohet Konfederatës", descSq: "Neuchâtel hyn në Konfederatë — duke mbetur një principatë prusiane (rast unik në Zvicër)." },
  { year: "1848", scope: "NE", title: "La République neuchâteloise",
    desc: "La révolution met fin à la principauté : Neuchâtel devient une République.",
    titleEn: "The Neuchâtel Republic", descEn: "The revolution ends the principality: Neuchâtel becomes a Republic.",
    titlePt: "A República de Neuchâtel", descPt: "A revolução põe fim ao principado: Neuchâtel torna-se uma República.",
    titleEs: "La República de Neuchâtel", descEs: "La revolución pone fin al principado: Neuchâtel se convierte en República.",
    titleIt: "La Repubblica di Neuchâtel", descIt: "La rivoluzione pone fine al principato: Neuchâtel diventa una Repubblica.",
    titleDe: "Die Republik Neuenburg", descDe: "Die Revolution beendet das Fürstentum: Neuenburg wird eine Republik.",
    titleSq: "Republika e Neuchâtel", descSq: "Revolucioni i jep fund principatës: Neuchâtel bëhet Republikë." },
  { year: "1849", scope: "NE", title: "Vote des étrangers",
    desc: "La Constitution accorde le droit de vote communal aux étrangers — une première en Suisse.",
    titleEn: "Foreigners' vote", descEn: "The Constitution grants foreigners the right to vote at communal level — a first in Switzerland.",
    titlePt: "Voto dos estrangeiros", descPt: "A Constituição concede o direito de voto municipal aos estrangeiros — uma primeira na Suíça.",
    titleEs: "Voto de los extranjeros", descEs: "La Constitución concede el derecho de voto municipal a los extranjeros — una primicia en Suiza.",
    titleIt: "Voto agli stranieri", descIt: "La Costituzione concede agli stranieri il diritto di voto comunale — una prima in Svizzera.",
    titleDe: "Stimmrecht für Ausländer", descDe: "Die Verfassung gewährt Ausländern das Stimmrecht auf Gemeindeebene — eine Premiere in der Schweiz.",
    titleSq: "Vota e të huajve", descSq: "Kushtetuta u jep të huajve të drejtën e votës komunale — një e parë në Zvicër." },
  { year: "2009", scope: "NE", title: "Urbanisme horloger à l'UNESCO",
    desc: "La Chaux-de-Fonds et Le Locle, villes de l'horlogerie, sont inscrites au patrimoine mondial.",
    titleEn: "Watchmaking towns at UNESCO", descEn: "La Chaux-de-Fonds and Le Locle, watchmaking towns, are listed as World Heritage.",
    titlePt: "Urbanismo relojoeiro na UNESCO", descPt: "La Chaux-de-Fonds e Le Locle, cidades da relojoaria, são inscritas no património mundial.",
    titleEs: "Urbanismo relojero en la UNESCO", descEs: "La Chaux-de-Fonds y Le Locle, ciudades relojeras, se inscriben en el patrimonio mundial.",
    titleIt: "Urbanistica orologiera all'UNESCO", descIt: "La Chaux-de-Fonds e Le Locle, città dell'orologeria, sono iscritte al patrimonio mondiale.",
    titleDe: "Uhrmacher-Städtebau bei der UNESCO", descDe: "La Chaux-de-Fonds und Le Locle, Uhrmacherstädte, werden ins Welterbe aufgenommen.",
    titleSq: "Urbanistika orëtare në UNESCO", descSq: "La Chaux-de-Fonds dhe Le Locle, qytete të orëtarisë, regjistrohen në trashëgiminë botërore." },

  /* -------- Valais -------- */
  { year: "1802", scope: "VS", title: "République du Valais",
    desc: "Éphémère République indépendante du Valais (République rhodanienne).",
    titleEn: "Republic of Valais", descEn: "The short-lived independent Republic of Valais (Rhodanic Republic).",
    titlePt: "República do Valais", descPt: "Efémera República independente do Valais (República Ródana).",
    titleEs: "República del Valais", descEs: "Efímera República independiente del Valais (República Ródana).",
    titleIt: "Repubblica del Vallese", descIt: "Effimera Repubblica indipendente del Vallese (Repubblica Rodanica).",
    titleDe: "Republik Wallis", descDe: "Die kurzlebige unabhängige Republik Wallis (Rhodanische Republik).",
    titleSq: "Republika e Valais", descSq: "Republika efemere e pavarur e Valais (Republika Rodaniane)." },
  { year: "1810", scope: "VS", title: "Annexion française",
    desc: "Napoléon annexe le Valais : il devient le département du Simplon.",
    titleEn: "French annexation", descEn: "Napoleon annexes Valais: it becomes the department of Simplon.",
    titlePt: "Anexação francesa", descPt: "Napoleão anexa o Valais: torna-se o departamento do Simplon.",
    titleEs: "Anexión francesa", descEs: "Napoleón anexiona el Valais: se convierte en el departamento del Simplón.",
    titleIt: "Annessione francese", descIt: "Napoleone annette il Vallese: diventa il dipartimento del Sempione.",
    titleDe: "Französische Annexion", descDe: "Napoleon annektiert das Wallis: Es wird zum Departement Simplon.",
    titleSq: "Aneksimi francez", descSq: "Napoleoni aneksohet Valais: bëhet departamenti i Simplonit." },
  { year: "1815", scope: "VS", title: "Le Valais rejoint la Confédération",
    desc: "Le Valais devient un canton suisse à part entière (23 cantons).",
    titleEn: "Valais joins the Confederation", descEn: "Valais becomes a full Swiss canton (23 cantons).",
    titlePt: "O Valais junta-se à Confederação", descPt: "O Valais torna-se um cantão suíço de pleno direito (23 cantões).",
    titleEs: "El Valais se une a la Confederación", descEs: "El Valais se convierte en un cantón suizo de pleno derecho (23 cantones).",
    titleIt: "Il Vallese entra nella Confederazione", descIt: "Il Vallese diventa un cantone svizzero a pieno titolo (23 cantoni).",
    titleDe: "Das Wallis tritt der Eidgenossenschaft bei", descDe: "Das Wallis wird ein vollwertiger Schweizer Kanton (23 Kantone).",
    titleSq: "Valais i bashkohet Konfederatës", descSq: "Valais bëhet një kanton zviceran i plotë (23 kantone)." },
  { year: "1865", scope: "VS", title: "Première ascension du Cervin",
    desc: "Edward Whymper gravit le Cervin depuis Zermatt ; la descente tourne au drame.",
    titleEn: "First ascent of the Matterhorn", descEn: "Edward Whymper climbs the Matterhorn from Zermatt; the descent ends in tragedy.",
    titlePt: "Primeira ascensão do Matterhorn", descPt: "Edward Whymper sobe o Matterhorn a partir de Zermatt; a descida acaba em tragédia.",
    titleEs: "Primera ascensión del Cervino", descEs: "Edward Whymper asciende el Cervino desde Zermatt; el descenso acaba en tragedia.",
    titleIt: "Prima ascensione del Cervino", descIt: "Edward Whymper scala il Cervino da Zermatt; la discesa finisce in tragedia.",
    titleDe: "Erstbesteigung des Matterhorns", descDe: "Edward Whymper besteigt das Matterhorn von Zermatt aus; der Abstieg endet in einer Tragödie.",
    titleSq: "Ngjitja e parë e Cervino-s", descSq: "Edward Whymper ngjit Cervino-n nga Zermatt; zbritja përfundon në tragjedi." },
  { year: "1964", scope: "VS", title: "Tunnel du Grand-Saint-Bernard",
    desc: "Ouverture du premier tunnel routier des Alpes, reliant le Valais à l'Italie.",
    titleEn: "Great St Bernard Tunnel", descEn: "Opening of the first road tunnel in the Alps, linking Valais to Italy.",
    titlePt: "Túnel do Grande São Bernardo", descPt: "Abertura do primeiro túnel rodoviário dos Alpes, ligando o Valais à Itália.",
    titleEs: "Túnel del Gran San Bernardo", descEs: "Apertura del primer túnel de carretera de los Alpes, que une el Valais con Italia.",
    titleIt: "Traforo del Gran San Bernardo", descIt: "Apertura del primo traforo stradale delle Alpi, che collega il Vallese all'Italia.",
    titleDe: "Grosser-St.-Bernhard-Tunnel", descDe: "Eröffnung des ersten Strassentunnels der Alpen, der das Wallis mit Italien verbindet.",
    titleSq: "Tuneli i Grand-Saint-Bernard", descSq: "Hapja e tunelit të parë rrugor të Alpeve, që lidh Valais me Italinë." },
];

if (typeof module !== "undefined") { module.exports = { TIMELINE }; }
