/* =========================================================================
 * Les 26 cantons suisses — données pour la carte interactive « Explorer la Suisse ».
 * x,y = position (centre) sur une carte-cartogramme schématique (viewBox 100×72),
 * approximativement géographique (ouest→est, nord→sud).
 * region : de = alémanique · fr = romand · it = italophone · multi = plurilingue.
 * name/langs/fact = FR (source) ; suffixes En/Pt/Es/It/De/Sq = traductions.
 * ========================================================================= */

const REGION_COLORS = { de: "#5B7DB1", fr: "#C65D3B", it: "#3C9E74", multi: "#B08A34" };
const REGION_LABEL = { de: "Alémanique", fr: "Romand", it: "Italophone", multi: "Plurilingue" };
const REGION_LABEL_EN = { de: "German", fr: "French", it: "Italian", multi: "Multilingual" };

const CANTONS = [
  { code: "ZH", name: "Zurich", capital: "Zurich", year: 1351, region: "de", langs: "Allemand", x: 48, y: 15, fact: "Plus grande ville et principal pôle économique et financier du pays.",
    nameEn: "Zurich", langsEn: "German", factEn: "The largest city and the country's main economic and financial hub.",
    namePt: "Zurique", langsPt: "Alemão", factPt: "A maior cidade e o principal polo económico e financeiro do país.",
    nameEs: "Zúrich", langsEs: "Alemán", factEs: "La mayor ciudad y el principal polo económico y financiero del país.",
    nameIt: "Zurigo", langsIt: "Tedesco", factIt: "La città più grande e il principale polo economico e finanziario del Paese.",
    nameDe: "Zürich", langsDe: "Deutsch", factDe: "Die grösste Stadt und das wichtigste Wirtschafts- und Finanzzentrum des Landes.",
    nameSq: "Cyrih", langsSq: "Gjermanisht", factSq: "Qyteti më i madh dhe poli kryesor ekonomik e financiar i vendit." },
  { code: "BE", name: "Berne", capital: "Berne", year: 1353, region: "multi", langs: "Allemand, Français", x: 31, y: 35, fact: "Abrite la ville fédérale ; 2ᵉ canton le plus peuplé.",
    nameEn: "Bern", langsEn: "German, French", factEn: "Home to the federal city; the 2nd most populous canton.",
    namePt: "Berna", langsPt: "Alemão, Francês", factPt: "Alberga a cidade federal; 2.º cantão mais populoso.",
    nameEs: "Berna", langsEs: "Alemán, Francés", factEs: "Alberga la ciudad federal; 2.º cantón más poblado.",
    nameIt: "Berna", langsIt: "Tedesco, Francese", factIt: "Ospita la città federale; 2º cantone più popoloso.",
    nameDe: "Bern", langsDe: "Deutsch, Französisch", factDe: "Beherbergt die Bundesstadt; zweitbevölkerungsreichster Kanton.",
    nameSq: "Bern", langsSq: "Gjermanisht, Frëngjisht", factSq: "Strehon qytetin federal; kantoni i 2-të më i populluar." },
  { code: "LU", name: "Lucerne", capital: "Lucerne", year: 1332, region: "de", langs: "Allemand", x: 38, y: 27, fact: "Son pont de la Chapelle est l'un des plus anciens ponts de bois d'Europe.",
    nameEn: "Lucerne", langsEn: "German", factEn: "Its Chapel Bridge is one of the oldest wooden bridges in Europe.",
    namePt: "Lucerna", langsPt: "Alemão", factPt: "A sua Ponte da Capela é uma das mais antigas pontes de madeira da Europa.",
    nameEs: "Lucerna", langsEs: "Alemán", factEs: "Su Puente de la Capilla es uno de los puentes de madera más antiguos de Europa.",
    nameIt: "Lucerna", langsIt: "Tedesco", factIt: "Il suo Ponte della Cappella è uno dei più antichi ponti di legno d'Europa.",
    nameDe: "Luzern", langsDe: "Deutsch", factDe: "Seine Kapellbrücke ist eine der ältesten Holzbrücken Europas.",
    nameSq: "Lucernë", langsSq: "Gjermanisht", factSq: "Ura e Kapelës është një nga urat prej druri më të vjetra në Evropë." },
  { code: "UR", name: "Uri", capital: "Altdorf", year: 1291, region: "de", langs: "Allemand", x: 51, y: 38, fact: "Canton fondateur de 1291, terre de la légende de Guillaume Tell.",
    nameEn: "Uri", langsEn: "German", factEn: "A founding canton of 1291, home of the William Tell legend.",
    namePt: "Uri", langsPt: "Alemão", factPt: "Cantão fundador de 1291, terra da lenda de Guilherme Tell.",
    nameEs: "Uri", langsEs: "Alemán", factEs: "Cantón fundador de 1291, tierra de la leyenda de Guillermo Tell.",
    nameIt: "Uri", langsIt: "Tedesco", factIt: "Cantone fondatore del 1291, terra della leggenda di Guglielmo Tell.",
    nameDe: "Uri", langsDe: "Deutsch", factDe: "Gründungskanton von 1291, Heimat der Wilhelm-Tell-Sage.",
    nameSq: "Uri", langsSq: "Gjermanisht", factSq: "Kanton themelues i 1291, vendi i legjendës së Vilhelm Telit." },
  { code: "SZ", name: "Schwytz", capital: "Schwytz", year: 1291, region: "de", langs: "Allemand", x: 52, y: 28, fact: "A donné son nom à la Suisse ; canton fondateur de 1291.",
    nameEn: "Schwyz", langsEn: "German", factEn: "Gave Switzerland its name; a founding canton of 1291.",
    namePt: "Schwyz", langsPt: "Alemão", factPt: "Deu o nome à Suíça; cantão fundador de 1291.",
    nameEs: "Schwyz", langsEs: "Alemán", factEs: "Dio su nombre a Suiza; cantón fundador de 1291.",
    nameIt: "Svitto", langsIt: "Tedesco", factIt: "Ha dato il nome alla Svizzera; cantone fondatore del 1291.",
    nameDe: "Schwyz", langsDe: "Deutsch", factDe: "Gab der Schweiz ihren Namen; Gründungskanton von 1291.",
    nameSq: "Schwyz", langsSq: "Gjermanisht", factSq: "I dha emrin Zvicrës; kanton themelues i 1291." },
  { code: "OW", name: "Obwald", capital: "Sarnen", year: 1291, region: "de", langs: "Allemand", x: 40, y: 39, fact: "Demi-canton ; patrie de Nicolas de Flüe, figure spirituelle de la Suisse.",
    nameEn: "Obwalden", langsEn: "German", factEn: "A half-canton; home of Nicholas of Flüe, a Swiss spiritual figure.",
    namePt: "Obwalden", langsPt: "Alemão", factPt: "Meio-cantão; pátria de Nicolau de Flüe, figura espiritual da Suíça.",
    nameEs: "Obwalden", langsEs: "Alemán", factEs: "Semicantón; patria de Nicolás de Flüe, figura espiritual de Suiza.",
    nameIt: "Obvaldo", langsIt: "Tedesco", factIt: "Semicantone; patria di Nicolao della Flüe, figura spirituale della Svizzera.",
    nameDe: "Obwalden", langsDe: "Deutsch", factDe: "Halbkanton; Heimat von Niklaus von Flüe, einer geistlichen Figur der Schweiz.",
    nameSq: "Obvald", langsSq: "Gjermanisht", factSq: "Gjysmëkanton; atdheu i Nikolla së Flüe-s, figurë shpirtërore e Zvicrës." },
  { code: "NW", name: "Nidwald", capital: "Stans", year: 1291, region: "de", langs: "Allemand", x: 45, y: 33, fact: "Demi-canton de Suisse centrale, au bord du lac des Quatre-Cantons.",
    nameEn: "Nidwalden", langsEn: "German", factEn: "A central-Switzerland half-canton, on Lake Lucerne.",
    namePt: "Nidwalden", langsPt: "Alemão", factPt: "Meio-cantão da Suíça central, à beira do lago de Lucerna.",
    nameEs: "Nidwalden", langsEs: "Alemán", factEs: "Semicantón de Suiza central, a orillas del lago de los Cuatro Cantones.",
    nameIt: "Nidvaldo", langsIt: "Tedesco", factIt: "Semicantone della Svizzera centrale, sul lago dei Quattro Cantoni.",
    nameDe: "Nidwalden", langsDe: "Deutsch", factDe: "Halbkanton der Zentralschweiz, am Vierwaldstättersee.",
    nameSq: "Nidvald", langsSq: "Gjermanisht", factSq: "Gjysmëkanton i Zvicrës qendrore, buzë liqenit të Katër Kantoneve." },
  { code: "GL", name: "Glaris", capital: "Glaris", year: 1352, region: "de", langs: "Allemand", x: 58, y: 31, fact: "Vote encore à main levée lors de sa Landsgemeinde annuelle.",
    nameEn: "Glarus", langsEn: "German", factEn: "Still votes by show of hands at its annual Landsgemeinde.",
    namePt: "Glaris", langsPt: "Alemão", factPt: "Vota ainda de braço no ar na sua Landsgemeinde anual.",
    nameEs: "Glaris", langsEs: "Alemán", factEs: "Aún vota a mano alzada en su Landsgemeinde anual.",
    nameIt: "Glarona", langsIt: "Tedesco", factIt: "Vota ancora per alzata di mano nella sua Landsgemeinde annuale.",
    nameDe: "Glarus", langsDe: "Deutsch", factDe: "Stimmt an seiner jährlichen Landsgemeinde noch per Handerheben ab.",
    nameSq: "Glarus", langsSq: "Gjermanisht", factSq: "Voton ende me ngritje dore në Landsgemeinde-n e tij vjetore." },
  { code: "ZG", name: "Zoug", capital: "Zoug", year: 1352, region: "de", langs: "Allemand", x: 47, y: 23, fact: "Petit canton réputé pour sa fiscalité avantageuse.",
    nameEn: "Zug", langsEn: "German", factEn: "A small canton known for its favourable taxation.",
    namePt: "Zug", langsPt: "Alemão", factPt: "Pequeno cantão conhecido pela sua fiscalidade vantajosa.",
    nameEs: "Zug", langsEs: "Alemán", factEs: "Pequeño cantón conocido por su fiscalidad ventajosa.",
    nameIt: "Zugo", langsIt: "Tedesco", factIt: "Piccolo cantone noto per la sua fiscalità vantaggiosa.",
    nameDe: "Zug", langsDe: "Deutsch", factDe: "Kleiner Kanton, bekannt für seine vorteilhafte Besteuerung.",
    nameSq: "Zug", langsSq: "Gjermanisht", factSq: "Kanton i vogël i njohur për fiskalitetin e tij të favorshëm." },
  { code: "FR", name: "Fribourg", capital: "Fribourg", year: 1481, region: "multi", langs: "Français, Allemand", x: 23, y: 36, fact: "Canton bilingue français-allemand ; patrie du fromage de Gruyère.",
    nameEn: "Fribourg", langsEn: "French, German", factEn: "A bilingual French–German canton; home of Gruyère cheese.",
    namePt: "Friburgo", langsPt: "Francês, Alemão", factPt: "Cantão bilingue francês-alemão; pátria do queijo Gruyère.",
    nameEs: "Friburgo", langsEs: "Francés, Alemán", factEs: "Cantón bilingüe francés-alemán; patria del queso Gruyère.",
    nameIt: "Friburgo", langsIt: "Francese, Tedesco", factIt: "Cantone bilingue francese-tedesco; patria del formaggio Gruyère.",
    nameDe: "Freiburg", langsDe: "Französisch, Deutsch", factDe: "Zweisprachiger französisch-deutscher Kanton; Heimat des Gruyère-Käses.",
    nameSq: "Friburg", langsSq: "Frëngjisht, Gjermanisht", factSq: "Kanton dygjuhësh frëngjisht-gjermanisht; atdheu i djathit Gruyère." },
  { code: "SO", name: "Soleure", capital: "Soleure", year: 1481, region: "de", langs: "Allemand", x: 26, y: 20, fact: "Ville baroque où le chiffre 11 est partout (tours, cloches, fontaines).",
    nameEn: "Solothurn", langsEn: "German", factEn: "A baroque town where the number 11 is everywhere (towers, bells, fountains).",
    namePt: "Solothurn", langsPt: "Alemão", factPt: "Cidade barroca onde o número 11 está por todo o lado (torres, sinos, fontes).",
    nameEs: "Soleura", langsEs: "Alemán", factEs: "Ciudad barroca donde el número 11 está por todas partes (torres, campanas, fuentes).",
    nameIt: "Soletta", langsIt: "Tedesco", factIt: "Città barocca dove il numero 11 è ovunque (torri, campane, fontane).",
    nameDe: "Solothurn", langsDe: "Deutsch", factDe: "Barockstadt, in der die Zahl 11 überall ist (Türme, Glocken, Brunnen).",
    nameSq: "Solothurn", langsSq: "Gjermanisht", factSq: "Qytet barok ku numri 11 është kudo (kulla, kambanë, shatërvanë)." },
  { code: "BS", name: "Bâle-Ville", capital: "Bâle", year: 1501, region: "de", langs: "Allemand", x: 16, y: 7, fact: "Demi-canton urbain : grand carnaval (Fasnacht) et industrie pharmaceutique.",
    nameEn: "Basel-City", langsEn: "German", factEn: "An urban half-canton: famous carnival (Fasnacht) and pharma industry.",
    namePt: "Basileia-Cidade", langsPt: "Alemão", factPt: "Meio-cantão urbano: grande carnaval (Fasnacht) e indústria farmacêutica.",
    nameEs: "Basilea-Ciudad", langsEs: "Alemán", factEs: "Semicantón urbano: gran carnaval (Fasnacht) e industria farmacéutica.",
    nameIt: "Basilea Città", langsIt: "Tedesco", factIt: "Semicantone urbano: grande carnevale (Fasnacht) e industria farmaceutica.",
    nameDe: "Basel-Stadt", langsDe: "Deutsch", factDe: "Städtischer Halbkanton: grosse Fasnacht und Pharmaindustrie.",
    nameSq: "Bazel-Qytet", langsSq: "Gjermanisht", factSq: "Gjysmëkanton urban: karnaval i madh (Fasnacht) dhe industri farmaceutike." },
  { code: "BL", name: "Bâle-Campagne", capital: "Liestal", year: 1501, region: "de", langs: "Allemand", x: 19, y: 15, fact: "Demi-canton, séparé de Bâle-Ville en 1833.",
    nameEn: "Basel-Country", langsEn: "German", factEn: "A half-canton, split from Basel-City in 1833.",
    namePt: "Basileia-Campo", langsPt: "Alemão", factPt: "Meio-cantão, separado de Basileia-Cidade em 1833.",
    nameEs: "Basilea-Campiña", langsEs: "Alemán", factEs: "Semicantón, separado de Basilea-Ciudad en 1833.",
    nameIt: "Basilea Campagna", langsIt: "Tedesco", factIt: "Semicantone, separato da Basilea Città nel 1833.",
    nameDe: "Basel-Landschaft", langsDe: "Deutsch", factDe: "Halbkanton, 1833 von Basel-Stadt getrennt.",
    nameSq: "Bazel-Fushatë", langsSq: "Gjermanisht", factSq: "Gjysmëkanton, i ndarë nga Bazel-Qyteti më 1833." },
  { code: "SH", name: "Schaffhouse", capital: "Schaffhouse", year: 1501, region: "de", langs: "Allemand", x: 49, y: 6, fact: "Au nord du Rhin ; on y admire les chutes du Rhin, les plus grandes d'Europe.",
    nameEn: "Schaffhausen", langsEn: "German", factEn: "North of the Rhine; home of the Rhine Falls, the largest in Europe.",
    namePt: "Schaffhausen", langsPt: "Alemão", factPt: "A norte do Reno; admiram-se as quedas do Reno, as maiores da Europa.",
    nameEs: "Schaffhausen", langsEs: "Alemán", factEs: "Al norte del Rin; se admiran las cataratas del Rin, las mayores de Europa.",
    nameIt: "Sciaffusa", langsIt: "Tedesco", factIt: "A nord del Reno; vi si ammirano le cascate del Reno, le più grandi d'Europa.",
    nameDe: "Schaffhausen", langsDe: "Deutsch", factDe: "Nördlich des Rheins; hier bestaunt man den Rheinfall, den grössten Europas.",
    nameSq: "Schaffhausen", langsSq: "Gjermanisht", factSq: "Në veri të Rinit; aty admirohet ujëvara e Rinit, më e madhja në Evropë." },
  { code: "AR", name: "Appenzell Rh.-Ext.", capital: "Herisau", year: 1513, region: "de", langs: "Allemand", x: 62, y: 17, fact: "Demi-canton d'Appenzell, de tradition protestante.",
    nameEn: "Appenzell A.Rh.", langsEn: "German", factEn: "An Appenzell half-canton, of Protestant tradition.",
    namePt: "Appenzell R.E.", langsPt: "Alemão", factPt: "Meio-cantão de Appenzell, de tradição protestante.",
    nameEs: "Appenzell R.E.", langsEs: "Alemán", factEs: "Semicantón de Appenzell, de tradición protestante.",
    nameIt: "Appenzello Esterno", langsIt: "Tedesco", factIt: "Semicantone dell'Appenzello, di tradizione protestante.",
    nameDe: "Appenzell Ausserrhoden", langsDe: "Deutsch", factDe: "Appenzeller Halbkanton protestantischer Tradition.",
    nameSq: "Appenzell Rh.-Jashtëm", langsSq: "Gjermanisht", factSq: "Gjysmëkanton i Appenzell-it, me traditë protestante." },
  { code: "AI", name: "Appenzell Rh.-Int.", capital: "Appenzell", year: 1513, region: "de", langs: "Allemand", x: 62, y: 24, fact: "Dernier canton à accorder le vote aux femmes (1990) ; Landsgemeinde.",
    nameEn: "Appenzell I.Rh.", langsEn: "German", factEn: "Last canton to grant women the vote (1990); Landsgemeinde.",
    namePt: "Appenzell R.I.", langsPt: "Alemão", factPt: "Último cantão a conceder o voto às mulheres (1990); Landsgemeinde.",
    nameEs: "Appenzell R.I.", langsEs: "Alemán", factEs: "Último cantón en dar el voto a las mujeres (1990); Landsgemeinde.",
    nameIt: "Appenzello Interno", langsIt: "Tedesco", factIt: "Ultimo cantone a concedere il voto alle donne (1990); Landsgemeinde.",
    nameDe: "Appenzell Innerrhoden", langsDe: "Deutsch", factDe: "Letzter Kanton, der den Frauen das Stimmrecht gab (1990); Landsgemeinde.",
    nameSq: "Appenzell Rh.-Brendshëm", langsSq: "Gjermanisht", factSq: "Kantoni i fundit që u dha grave të drejtën e votës (1990); Landsgemeinde." },
  { code: "SG", name: "Saint-Gall", capital: "Saint-Gall", year: 1803, region: "de", langs: "Allemand", x: 70, y: 21, fact: "Sa bibliothèque abbatiale est inscrite au patrimoine mondial de l'UNESCO.",
    nameEn: "St. Gallen", langsEn: "German", factEn: "Its abbey library is a UNESCO World Heritage Site.",
    namePt: "São Galo", langsPt: "Alemão", factPt: "A sua biblioteca abacial é Património Mundial da UNESCO.",
    nameEs: "San Galo", langsEs: "Alemán", factEs: "Su biblioteca abacial es Patrimonio Mundial de la UNESCO.",
    nameIt: "San Gallo", langsIt: "Tedesco", factIt: "La sua biblioteca abbaziale è Patrimonio Mondiale dell'UNESCO.",
    nameDe: "St. Gallen", langsDe: "Deutsch", factDe: "Seine Stiftsbibliothek ist UNESCO-Weltkulturerbe.",
    nameSq: "San Gal", langsSq: "Gjermanisht", factSq: "Biblioteka e tij abaciale është Trashëgimi Botërore e UNESCO-s." },
  { code: "GR", name: "Grisons", capital: "Coire", year: 1803, region: "multi", langs: "Allemand, Romanche, Italien", x: 69, y: 37, fact: "Plus grand canton et seul trilingue (allemand, romanche, italien).",
    nameEn: "Grisons", langsEn: "German, Romansh, Italian", factEn: "The largest canton and the only trilingual one (German, Romansh, Italian).",
    namePt: "Grisões", langsPt: "Alemão, Romanche, Italiano", factPt: "O maior cantão e o único trilingue (alemão, romanche, italiano).",
    nameEs: "Grisones", langsEs: "Alemán, Romanche, Italiano", factEs: "El cantón más grande y el único trilingüe (alemán, romanche, italiano).",
    nameIt: "Grigioni", langsIt: "Tedesco, Romancio, Italiano", factIt: "Il cantone più grande e l'unico trilingue (tedesco, romancio, italiano).",
    nameDe: "Graubünden", langsDe: "Deutsch, Rätoromanisch, Italienisch", factDe: "Der grösste Kanton und der einzige dreisprachige (Deutsch, Rätoromanisch, Italienisch).",
    nameSq: "Graubünden", langsSq: "Gjermanisht, Retoromanisht, Italisht", factSq: "Kantoni më i madh dhe i vetmi trigjuhësh (gjermanisht, retoromanisht, italisht)." },
  { code: "AG", name: "Argovie", capital: "Aarau", year: 1803, region: "de", langs: "Allemand", x: 35, y: 14, fact: "Surnommé le « canton des châteaux ».",
    nameEn: "Aargau", langsEn: "German", factEn: "Nicknamed the « canton of castles ».",
    namePt: "Argóvia", langsPt: "Alemão", factPt: "Apelidado de « cantão dos castelos ».",
    nameEs: "Argovia", langsEs: "Alemán", factEs: "Apodado el « cantón de los castillos ».",
    nameIt: "Argovia", langsIt: "Tedesco", factIt: "Soprannominato il « cantone dei castelli ».",
    nameDe: "Aargau", langsDe: "Deutsch", factDe: "Wird der « Kanton der Schlösser » genannt.",
    nameSq: "Argovi", langsSq: "Gjermanisht", factSq: "I mbiquajtur « kantoni i kështjellave »." },
  { code: "TG", name: "Thurgovie", capital: "Frauenfeld", year: 1803, region: "de", langs: "Allemand", x: 59, y: 10, fact: "Pays des vergers et des pommes, au bord du lac de Constance.",
    nameEn: "Thurgau", langsEn: "German", factEn: "Land of orchards and apples, on Lake Constance.",
    namePt: "Thurgau", langsPt: "Alemão", factPt: "Terra dos pomares e das maçãs, à beira do lago de Constança.",
    nameEs: "Turgovia", langsEs: "Alemán", factEs: "Tierra de huertos y manzanas, a orillas del lago de Constanza.",
    nameIt: "Turgovia", langsIt: "Tedesco", factIt: "Terra di frutteti e mele, sul lago di Costanza.",
    nameDe: "Thurgau", langsDe: "Deutsch", factDe: "Land der Obstgärten und Äpfel, am Bodensee.",
    nameSq: "Turgovi", langsSq: "Gjermanisht", factSq: "Vend i pemishteve dhe i mollëve, buzë liqenit të Konstancës." },
  { code: "TI", name: "Tessin", capital: "Bellinzone", year: 1803, region: "it", langs: "Italien", x: 55, y: 61, fact: "Seul canton de langue italienne ; les châteaux de Bellinzone sont à l'UNESCO.",
    nameEn: "Ticino", langsEn: "Italian", factEn: "The only Italian-speaking canton; the castles of Bellinzona are UNESCO-listed.",
    namePt: "Tessino", langsPt: "Italiano", factPt: "Único cantão de língua italiana; os castelos de Bellinzona são Património da UNESCO.",
    nameEs: "Tesino", langsEs: "Italiano", factEs: "Único cantón de lengua italiana; los castillos de Bellinzona son Patrimonio de la UNESCO.",
    nameIt: "Ticino", langsIt: "Italiano", factIt: "Unico cantone di lingua italiana; i castelli di Bellinzona sono Patrimonio UNESCO.",
    nameDe: "Tessin", langsDe: "Italienisch", factDe: "Der einzige italienischsprachige Kanton; die Burgen von Bellinzona sind UNESCO-Welterbe.",
    nameSq: "Tiçino", langsSq: "Italisht", factSq: "Kantoni i vetëm italishtfolës; kështjellat e Bellinzona-s janë Trashëgimi UNESCO." },
  { code: "VD", name: "Vaud", capital: "Lausanne", year: 1803, region: "fr", langs: "Français", x: 13, y: 45, fact: "Terrasses de Lavaux (UNESCO) ; Lausanne, capitale olympique.",
    nameEn: "Vaud", langsEn: "French", factEn: "Lavaux terraces (UNESCO); Lausanne, the Olympic Capital.",
    namePt: "Vaud", langsPt: "Francês", factPt: "Terraços de Lavaux (UNESCO); Lausanne, capital olímpica.",
    nameEs: "Vaud", langsEs: "Francés", factEs: "Terrazas de Lavaux (UNESCO); Lausana, capital olímpica.",
    nameIt: "Vaud", langsIt: "Francese", factIt: "Terrazze di Lavaux (UNESCO); Losanna, capitale olimpica.",
    nameDe: "Waadt", langsDe: "Französisch", factDe: "Lavaux-Terrassen (UNESCO); Lausanne, die olympische Hauptstadt.",
    nameSq: "Vaud", langsSq: "Frëngjisht", factSq: "Tarracat e Lavaux (UNESCO); Lozana, kryeqyteti olimpik." },
  { code: "VS", name: "Valais", capital: "Sion", year: 1815, region: "multi", langs: "Français, Allemand", x: 33, y: 53, fact: "Bilingue ; abrite le Cervin et la Pointe Dufour, plus haut sommet du pays.",
    nameEn: "Valais", langsEn: "French, German", factEn: "Bilingual; home of the Matterhorn and Dufourspitze, the country's highest peak.",
    namePt: "Valais", langsPt: "Francês, Alemão", factPt: "Bilingue; alberga o Matterhorn e a Pointe Dufour, ponto mais alto do país.",
    nameEs: "Valais", langsEs: "Francés, Alemán", factEs: "Bilingüe; alberga el Cervino y la Punta Dufour, la cima más alta del país.",
    nameIt: "Vallese", langsIt: "Francese, Tedesco", factIt: "Bilingue; ospita il Cervino e la Punta Dufour, la vetta più alta del Paese.",
    nameDe: "Wallis", langsDe: "Französisch, Deutsch", factDe: "Zweisprachig; beheimatet das Matterhorn und die Dufourspitze, den höchsten Gipfel des Landes.",
    nameSq: "Valais", langsSq: "Frëngjisht, Gjermanisht", factSq: "Dygjuhësh; strehon Cervino-n dhe Majën Dufour, maja më e lartë e vendit." },
  { code: "NE", name: "Neuchâtel", capital: "Neuchâtel", year: 1815, region: "fr", langs: "Français", x: 15, y: 28, fact: "Berceau de l'horlogerie de précision.",
    nameEn: "Neuchâtel", langsEn: "French", factEn: "The cradle of precision watchmaking.",
    namePt: "Neuchâtel", langsPt: "Francês", factPt: "Berço da relojoaria de precisão.",
    nameEs: "Neuchâtel", langsEs: "Francés", factEs: "Cuna de la relojería de precisión.",
    nameIt: "Neuchâtel", langsIt: "Francese", factIt: "Culla dell'orologeria di precisione.",
    nameDe: "Neuenburg", langsDe: "Französisch", factDe: "Wiege der Präzisionsuhrmacherei.",
    nameSq: "Neuchâtel", langsSq: "Frëngjisht", factSq: "Djepi i orëtarisë së precizionit." },
  { code: "GE", name: "Genève", capital: "Genève", year: 1815, region: "fr", langs: "Français", x: 6, y: 58, fact: "Ville internationale : siège européen de l'ONU, célèbre jet d'eau.",
    nameEn: "Geneva", langsEn: "French", factEn: "An international city: European seat of the UN, famous water jet.",
    namePt: "Genebra", langsPt: "Francês", factPt: "Cidade internacional: sede europeia da ONU, famoso jato de água.",
    nameEs: "Ginebra", langsEs: "Francés", factEs: "Ciudad internacional: sede europea de la ONU, famoso chorro de agua.",
    nameIt: "Ginevra", langsIt: "Francese", factIt: "Città internazionale: sede europea dell'ONU, celebre getto d'acqua.",
    nameDe: "Genf", langsDe: "Französisch", factDe: "Internationale Stadt: europäischer UNO-Sitz, berühmter Wasserstrahl (Jet d'eau).",
    nameSq: "Gjenevë", langsSq: "Frëngjisht", factSq: "Qytet ndërkombëtar: selia evropiane e OKB-së, shatërvani i famshëm." },
  { code: "JU", name: "Jura", capital: "Delémont", year: 1979, region: "fr", langs: "Français", x: 10, y: 20, fact: "Le plus jeune canton, créé en 1979 en se séparant de Berne.",
    nameEn: "Jura", langsEn: "French", factEn: "The youngest canton, created in 1979 by splitting from Bern.",
    namePt: "Jura", langsPt: "Francês", factPt: "O cantão mais jovem, criado em 1979 ao separar-se de Berna.",
    nameEs: "Jura", langsEs: "Francés", factEs: "El cantón más joven, creado en 1979 al separarse de Berna.",
    nameIt: "Giura", langsIt: "Francese", factIt: "Il cantone più giovane, creato nel 1979 separandosi da Berna.",
    nameDe: "Jura", langsDe: "Französisch", factDe: "Der jüngste Kanton, 1979 durch Abspaltung von Bern entstanden.",
    nameSq: "Jura", langsSq: "Frëngjisht", factSq: "Kantoni më i ri, krijuar më 1979 duke u ndarë nga Berna." },
];

if (typeof module !== "undefined") { module.exports = { CANTONS, REGION_COLORS, REGION_LABEL, REGION_LABEL_EN }; }
